### ISSUE TITLE
Installation failing with Error 1

### ISSUE THREAD

**Issue by JikkuJose** [smazga/conkeror_mac_bundler#3]
Any ideas why this happening?

`mkdir -p Conkeror.app/Contents/MacOS`
`cp -rp /Applications/Firefox.app/Contents/MacOS/* Conkeror.app/Contents/MacOS`
`mkdir -p Conkeror.app/Contents/MacOS/conkeror/conkeror`
`copying files...`
`cp: conkeror.git/application.ini: No such file or directory`
`cp: conkeror.git/chrome.manifest: No such file or directory`
`cp: conkeror.git/content-policy.manifest: No such file or directory`
`make: *** [Conkeror.app/Contents/MacOS/conkeror] Error 1`

My system:
1. I have xcode command line tools.
2. I am running on 10.9.2
3. I do have Firefox

**Comment by smazga** [comment]
There was a missing dependency (the git repo wasn't cloned before attempting to copy files).

Fixed in ba4191db6ae9a3bc90868512d99b8458eaa9780e
