### ISSUE TITLE
Not working with Firefox 35.0.1

### ISSUE THREAD

**Issue by tjim** [smazga/conkeror_mac_bundler#4]
The Conkeror.app produced does not work. Nothing happens when the app is opened, whether from finder or command line (with open -a).

Looking at the Firefox.app, it seems like the directory structure has changed compared to earlier versions I've used. Perhaps XULrunner conventions have been changed.

I haven't had a chance to debug this yet.

**Comment by smazga** [comment]
Yeah, I'm getting "Couldn't load XPCOM". They made some bundling changes for Yosemite, which may be the source of the problem, but it's not clear what I need to do to fix it, yet.

**Comment by tjim** [comment]
At some point I got it working with firefox 34, but it was a brute force solution---I just copied conkeror files in imitation of the firefox directory structure. So there are probably extra files.
However, there's an easy way to see what files are opened by an app (opensnoop), so I did this. Should provide a good road map.
Here are the files in the Conkeror.app directory opened by conkeror (based on firefox 34) on startup from command line. Not all are opened by the firefox process.

    COMM          FD PATH
    taskgated      3 /Users/trevor/Applications/Conkeror.app/Contents 
    taskgated      3 /Users/trevor/Applications/Conkeror.app/Contents/Info.plist 
    taskgated      3 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/firefox-bin 
    firefox-bin    3 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./libmozglue.dylib 
    firefox-bin    3 /Users/trevor/Applications/Conkeror.app 
    firefox-bin    3 /Users/trevor/Applications/Conkeror.app/Contents 
    firefox-bin    3 /Users/trevor/Applications/Conkeror.app/Contents/Info.plist 
    firefox-bin    3 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./firefox-bin 
    firefox-bin    3 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./dependentlibs.list 
    firefox-bin    4 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./libmozglue.dylib 
    firefox-bin    4 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./libnss3.dylib 
    firefox-bin    4 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./libmozalloc.dylib 
    firefox-bin    4 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./XUL 
    firefox-bin    4 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./libnss3.dylib 
    taskgated      3 /Users/trevor/Applications/Conkeror.app 
    firefox-bin    4 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./libmozalloc.dylib 
    firefox-bin    3 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/application.ini 
    firefox-bin   -1 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./distribution/bundles 
    firefox-bin    7 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./defaults/pref/channel-prefs.js 
    firefox-bin    7 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/defaults/preferences 
    firefox-bin    7 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/defaults/preferences/prefs.js 
    firefox-bin    7 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/defaults/preferences/gui.js 
    firefox-bin    7 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/defaults/preferences/download-manager.js 
    firefox-bin    7 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/defaults/preferences/default-modules.js 
    firefox-bin    4 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./XUL 
    firefox-bin   -1 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./updates/0/update.status 
    firefox-bin    7 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./omni.ja 
    firefox-bin    7 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./defaults/pref 
    firefox-bin    7 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/defaults/preferences/uri.js 
    firefox-bin    7 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/defaults/preferences/javascript-restrictions.js 
    firefox-bin    7 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/defaults/preferences/history-frecency.js 
    firefox-bin    7 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/defaults/preferences/debug.js 
    firefox-bin   10 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/chrome/chrome.manifest 
    firefox-bin    9 /Users/trevor/Applications/Conkeror.app/Contents/Resources 
    firefox-bin    9 /Users/trevor/Applications/Conkeror.app/Contents/Resources/en.lproj 
    firefox-bin   -1 /Users/trevor/Applications/Conkeror.app/Contents/Resources/Base.lproj 
    firefox-bin   -1 /Users/trevor/Applications/Conkeror.app/Contents/Resources/English.lproj 
    firefox-bin    9 /Users/trevor/Applications/Conkeror.app/Contents/Resources/en.lproj/InfoPlist.strings 
    launchservicesd   4 /Users/trevor/Applications/Conkeror.app 
    launchservicesd   4 /Users/trevor/Applications/Conkeror.app/Contents 
    launchservicesd   4 /Users/trevor/Applications/Conkeror.app/Contents/Info.plist 
    launchservicesd   4 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/firefox-bin 
    firefox-bin   19 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./res/MainMenu.nib/keyedobjects.nib 
    diagnostics_age  -1 /Users/trevor/Applications/Conkeror.app/Contents/_MASReceipt/receipt 
    firefox-bin   -1 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./chrome.manifest 
    firefox-bin    9 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/chrome.manifest 
    firefox-bin    9 /Users/trevor/Applications/Conkeror.app/Contents/Resources 
    com.apple.CodeS   4 /Users/trevor/Applications/Conkeror.app 
    com.apple.CodeS   4 /Users/trevor/Applications/Conkeror.app/Contents 
    com.apple.CodeS   4 /Users/trevor/Applications/Conkeror.app/Contents/Info.plist 
    Dock          -1 /Users/trevor/Applications/Conkeror.app/Contents/PkgInfo 
    Dock          26 /Users/trevor/Applications/Conkeror.app 
    Dock          26 /Users/trevor/Applications/Conkeror.app/Contents 
    Dock          26 /Users/trevor/Applications/Conkeror.app/Contents/Info.plist 
    firefox-bin   19 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/branding/brand.dtd 
    firefox-bin   19 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/omni.ja 
    firefox-bin    3 /Users/trevor/Applications/Conkeror.app 
    firefox-bin    3 /Users/trevor/Applications/Conkeror.app/Contents 
    firefox-bin    3 /Users/trevor/Applications/Conkeror.app/Contents/Info.plist 
    firefox-bin    3 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./firefox-bin 
    firefox-bin    3 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./dependentlibs.list 
    firefox-bin    4 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./libmozglue.dylib 
    firefox-bin    4 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./libnss3.dylib 
    firefox-bin    4 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./libnss3.dylib 
    firefox-bin    4 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./libmozalloc.dylib 
    firefox-bin    4 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./libmozalloc.dylib 
    firefox-bin    4 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./XUL 
    firefox-bin   20 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/branding/brand.properties 
    taskgated      3 /Users/trevor/Applications/Conkeror.app 
    taskgated      3 /Users/trevor/Applications/Conkeror.app/Contents 
    taskgated      3 /Users/trevor/Applications/Conkeror.app/Contents/Info.plist 
    taskgated      3 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/firefox-bin 
    firefox-bin    4 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./XUL 
    firefox-bin    3 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./libmozglue.dylib 
    firefox-bin   -1 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./distribution/bundles 
    launchservicesd   4 /Users/trevor/Applications/Conkeror.app 
    launchservicesd   4 /Users/trevor/Applications/Conkeror.app/Contents 
    launchservicesd   4 /Users/trevor/Applications/Conkeror.app/Contents/Info.plist 
    launchservicesd   4 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/firefox-bin 
    Dock          -1 /Users/trevor/Applications/Conkeror.app/Contents/PkgInfo 
    Dock          26 /Users/trevor/Applications/Conkeror.app 
    Dock          26 /Users/trevor/Applications/Conkeror.app/Contents 
    Dock          26 /Users/trevor/Applications/Conkeror.app/Contents/Info.plist 
    firefox-bin    3 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/application.ini 
    firefox-bin    4 /Users/trevor/Applications/Conkeror.app/Contents/Resources 
    firefox-bin    4 /Users/trevor/Applications/Conkeror.app/Contents/Resources 
    firefox-bin    4 /Users/trevor/Applications/Conkeror.app/Contents/Resources/en.lproj 
    firefox-bin   -1 /Users/trevor/Applications/Conkeror.app/Contents/Resources/Base.lproj 
    firefox-bin   -1 /Users/trevor/Applications/Conkeror.app/Contents/Resources/English.lproj 
    firefox-bin    4 /Users/trevor/Applications/Conkeror.app/Contents/Resources/en.lproj/InfoPlist.strings 
    com.apple.CodeS   4 /Users/trevor/Applications/Conkeror.app 
    com.apple.CodeS   4 /Users/trevor/Applications/Conkeror.app/Contents 
    com.apple.CodeS   4 /Users/trevor/Applications/Conkeror.app/Contents/Info.plist 
    diagnostics_age  -1 /Users/trevor/Applications/Conkeror.app/Contents/_MASReceipt/receipt 
    firefox-bin   32 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./omni.ja 
    firefox-bin   34 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./res/MainMenu.nib/keyedobjects.nib 
    firefox-bin   34 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/omni.ja 
    firefox-bin   -1 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./updates/0/update.status 
    firefox-bin   32 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./defaults/pref 
    firefox-bin   32 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./defaults/pref/channel-prefs.js 
    firefox-bin   32 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/defaults/preferences 
    firefox-bin   32 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/defaults/preferences/uri.js 
    firefox-bin   32 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/defaults/preferences/prefs.js 
    firefox-bin   32 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/defaults/preferences/javascript-restrictions.js 
    firefox-bin   32 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/defaults/preferences/history-frecency.js 
    firefox-bin   32 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/defaults/preferences/gui.js 
    firefox-bin   32 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/defaults/preferences/download-manager.js 
    firefox-bin   32 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/defaults/preferences/default-modules.js 
    firefox-bin   32 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/defaults/preferences/debug.js 
    firefox-bin   -1 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./chrome.manifest 
    firefox-bin   34 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/chrome.manifest 
    firefox-bin   35 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/chrome/chrome.manifest 
    firefox-bin   36 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/components/application.js 
    firefox-bin   36 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/hook.js 
    firefox-bin   36 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/timer.js 
    firefox-bin   36 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/services.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/string.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/env.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/source-code.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/user-variable.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/stylesheet.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/builtin-commands.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/interactive.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/text.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/login.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/user-agent.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/dom.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/minibuffer.js 
    firefox-bin   36 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/components/command-line.js 
    firefox-bin   36 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/conkeror.js 
    firefox-bin   36 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/keywords.js 
    firefox-bin   36 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/labels.js 
    firefox-bin   36 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/pretty-print.js 
    firefox-bin   36 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/debug.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/pref.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/array.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/utils.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/io.js 
    firefox-bin   36 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/coroutine.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/completers.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/mime.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/keymap.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/input.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/window.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/mode.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/buffer.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/mime-type-override.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/special-buffer.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/minibuffer-read-mime-type.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/compat/Map.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/element.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/hints.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/content/minibuffer-annotation.css 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/save.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/content-buffer.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/load-spec.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/webjump.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/history.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/suggest-file-name.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/quote.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/universal-argument.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/commands.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/zoom.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/follow-relationship.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/isearch.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/help.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/rc.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/ssl.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/media.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/command-line.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/opensearch.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/search-engines/google.xml 
    firefox-bin   40 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/search-engines/mozilla-bugzilla.xml 
    firefox-bin   41 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/search-engines/wikipedia.xml 
    firefox-bin   42 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/search-engines/wiktionary.xml 
    firefox-bin   43 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/search-engines/answers.xml 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/minibuffer-read.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/minibuffer-read-option.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/minibuffer-read-file.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/spawn-process.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/content-handler.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/content/hints.css 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/content-buffer-input.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/caret.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/scroll.js 
    firefox-bin   39 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/download-manager.js 
    firefox-bin   44 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/search-engines/yahoo.xml 
    firefox-bin   45 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/search-engines/creativecommons.xml 
    firefox-bin   46 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/search-engines/eBay.xml 
    firefox-bin   47 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/search-engines/duckduckgo.xml 
    firefox-bin   48 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/permission-manager.js 
    firefox-bin   48 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/cookie.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/cache.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/theme.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/style/default/minibuffer.css 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/formfill.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/page-modes/google-reader.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/daemon.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/style/default/mode-line.css 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/page-modes/google-video.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/page-modes/google-maps.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/page-modes/youtube.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/bindings.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/basic-commands.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/global.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/text.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/formfill.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/content-buffer/anchor.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/content-buffer/form.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/content-buffer/text.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/content-buffer/checkbox.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/content-buffer/textarea.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/content-buffer/select.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/content-buffer/embed.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/minibuffer.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/hints.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/universal-argument.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/content-buffer/element.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/content-buffer/zoom.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/special-buffer.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/help-buffer.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/download-buffer.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/caret.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/quote.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/style/default/theme.json 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/style/default/content-buffer-input.css 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/style/default/window--panel.css 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/external-editor.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/page-modes/google-calendar.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/mode-line.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/page-modes/dailymotion.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/content-buffer/normal.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/content-buffer/richedit.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/content-buffer/button.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/bindings/default/isearch.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/page-modes/smbc.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/page-modes/grooveshark.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/page-modes/youtube-player.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/page-modes/stackexchange.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/content-policy.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/clicks-in-new-buffer.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/session.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/extensions/noscript.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./libsoftokn3.dylib 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./libfreebl3.dylib 
    firefox-bin   55 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./libnssckbi.dylib 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/modules/page-modes/xkcd.js 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/content-policy.manifest 
    firefox-bin   53 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./libnssdbm3.dylib 
    firefox-bin   55 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/content/conkeror.xul 
    firefox-bin   52 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/components/content-policy.js 
    firefox-bin   52 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/content/minibuffer.xul 
    firefox-bin   52 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/content/minibuffer.css 
    firefox-bin   52 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/conkeror/content/annotated-textbox.xml 
    firefox-bin   89 /Users/trevor/Applications/Conkeror.app/Contents/MacOS/./dictionaries

**Comment by rohni** [comment]
@tjim Can you recount the steps you took to manually hack together something that worked, and how you started it?  I have the same problem with firefox 35 and even copying files around has not helped.  I do notice that I don't have omni.ja (not sure what that is) and a bunch of stuff in the Resources directory is missing.  I would love to have conkeror back.  I have been trying to hack something together with firefox plugins, but it is a sad replacement. :(  

P.S. I see that JJFoerch is thinking of a different platform for the 2.0 version, I am curious as to what, as xulrunner is pretty much dead on the mac, I hope it will be an improvement. :)

**Comment by smazga** [comment]
Since xulrunner is so weirdly managed in Firefox releases, I decided to punt and just have the installer download a known version and build the app bundle from that.

Commit 35c12979fc5e2d96b0978410be0caa6f918e69ab has a new 'install.sh' script that will install with xulrunner 33.1.1. I switched to a shell script instead of a makefile, because using make felt forced, and it doesn't seem to handle directory dependencies well.

Note: it installs in ~/Applications now instead of /Applications, just because I felt that was more appropriate, but we can switch it back if the general consensus leans that way.

**Comment by rohni** [comment]
Thanks, it works perfectly. :+1:

**Comment by tjim** [comment]
Why 33.1.1 and not the latest 35.0.1? Did you have trouble with 35.0.1?
I tried 35.0.1 and it did not work for me.
However, I have it working now. The fix is to add the file Contents/Resources/dependentlibs.list
I just grabbed it from Firefox.app. Its contents are:

libmozglue.dylib
libnss3.dylib
libmozalloc.dylib
XUL

**Comment by smazga** [comment]
I went with 33.1.1 because 35 and 34 both just bailed with "Couldn't load XPCOM". I could have spent time investigating, but it worked before, so I knew it would probably work again given the right version. And 2 versions back doesn't seem that bad, for conkeror use (that's like what, a week of Firefox development?).

Since you went to the trouble of figuring out the magic, though, I'll see if it can be tweaked to just use 'latest' xulrunner.

I like not having Firefox as a dependency, though. That always felt sort of lame.

**Comment by smazga** [comment]
Your fix worked, tjim, so the script now builds against 35.0.1.

It's hard-coded for now, but I'll try to tweak it to follow 'latest' at some point.
