### ISSUE TITLE
Error Installing (xulrunner 35.0.1 not available)

### ISSUE THREAD

**Issue by jkd00** [smazga/conkeror_mac_bundler#5]
Hey there,

Trying to install this on OS X 9.5. When running ./install.sh it fails at downloading xulrunner:

(7) Failed connect to ftp.mozilla.org:21; Operation timed out

However, some poking around showed the file was available over http. I edited the install.sh file and changed ftp to http on line 26 and it worked. Downloaded, installed and runs perfectly.

**Comment by smazga** [comment]
Thanks!

Fixed in ea59f5f4d02109daea4f96df97212f6716c69073

I guess "ftp" doesn't mean ftp any more.
